WorldEnterpriseGroup/reveltek

index.html

i changed a few words to Welcome to Reveltek

Updated copywriting

---

index.html

I changed the header of the website to Technical Consulting

header update

---

services-2.html

Updated the description under the Business strategy of services 2

Updated services-2.html

---

Notes/Latestarticles.md

Created the file for our Articles under the issue# 34

Our Latest Articles

---

Notes/Insideservices.md

Created file on market research for inside pages of services.

Insideservices.md

---

Notes/Industries.md

Created a file of "Our Industries" for RevelTek.

Our Industries

---

Notes/Important Articles

Created a file for "Important Articles" section.

Important Articles

---

Notes/Our careers.md

Created a .md file of careers with RevelTek according to STAR.

Career with us

---

services.html

Updated the spellings of does in the title of services.html

Updated services.html

---

Notes/Our Insights.md

Created a .md file for "Our insights" while considering all the steps for research marketing.

Our Insights

---

Notes/Important Articles

Updated "Important Articles" file.

Update Important Articles

---

Notes/Our Insights.md

Updated headings for Insights.

Update Our Insights.md

---

Notes/Industries Research Analysis for Reveltek.md

Here you can find Industries Research Analysis for Reveltek website.

Create Industries Research folder.md

---

Notes/NAICS Code Research for Reveltek

Here you will find the relevant NAICS and SIC Code for what I think should align with Reveltek services.

Create NAICS Code Research for Reveltek

---

Notes/NAICS Code.md

Created a file of NAICS code for Tech consulting firm.

NAICS Code

---

Notes/NAICS code for RevelTek.md

Created a file for NAICS Codes.

NAICS file for RevelTek

---

Notes/NAICS Code.md

Updated NAICS Code.md

---

Notes/NAICS code for RevelTek.md

Updated the NAICS code for RevelTek.md file.

NAICS code for RevelTek.md

---

Notes/Article Ideas for Reveltek Website.md

Here you will find some of the ideas for the Articles of Reveltek Website.

Create Article Ideas for Reveltek Website.md

---

Notes/Best Profiles.md

Updated their names with links to their profile.

GitHub Best Profile Participants List

---

services.html

Updated the content as per the requirement of the issue.

Updated the Section as per issue #20

---

Notes/STAR Intro.md

Updated notes on my understanding of new STAR approach

STAR approach notes
